/**
 * # Build Script
 * 
 * Script executed as a final build step.
 * 
 * * Renames files generated by TypeScript.
 * 
 * @moduleBB
 */

const fs = require("fs");

const names = ["index", "sync_agent", "messages"];

for (const name of names) {
  const file_path = `./worker/${name}.mjs.js`;
  
  if (fs.existsSync(file_path)) {
    const new_path = `./worker/${name}.mjs`;
    
    fs.rename(file_path, new_path, (err) => {
      if (err) { console.log("ERROR:", err); } 
    });
  }
}
